### ISSUE TITLE
Add `documentationUrl` to each spectral rule

### ISSUE THREAD

**Issue by milkshakeuk** [ukhsa-collaboration/api-guidelines#21]
### Description:
Add a `documentationUrl` field to each Spectral rule to provide links to detailed documentation or resources in the linting output. This will enable developers to access extra context about rule violations directly from the output.

### Benefits:
- Saves time for developers by reducing the need to search for external documentation manually.
- Improves understanding of rule violations and how to resolve them.
- Enhances the usability and adoption of Spectral rules by offering actionable guidance.

### Acceptance Criteria
- Existing rules are updated  to contain the `documentationUrl` field with appropriate documentation URLs.

#### Example:
```yaml
rules:
  no-empty-description:
    description: "Descriptions should not be empty."
    severity: error
    documentationUrl: "https://docs.example.com/spectral/rules/no-empty-description"
   ...
```

### Proposed Steps:
1. Update existing rules to include the `documentationUrl` property with the relevant documentation URLs.
2. Modify the spectral cli usage examples to use the new `--show-documentation-url` flag 
3. Provide guidelines for adding `documentationUrl` to new rules in the future.

### Additional Info/Context:
- This feature was enabled in the [latest release `6.15.0`](https://github.com/stoplightio/spectral/releases/tag/v6.15.0) of the spectral cli
- This feature aligns with similar functionalities in other linters like ESLint, which use a `docs` property for rules.
- Consistent documentation URLs will improve the overall developer experience and encourage best practices.

### References:
- [Spectral Documentation](https://docs.stoplight.io/docs/spectral)
- [ESLint Rule Docs](https://eslint.org/docs/latest/rules/)
