### ISSUE TITLE
Create spectral rule to mandate common error responses

### ISSUE THREAD

**Issue by milkshakeuk** [ukhsa-collaboration/api-guidelines#5]
### Mandatory Error Responses

Create a rule that mandates common error responses (`401`, `403`, `404`, `500` etc.) using the `ProblemDetails` standard ([RFC-9457](https://www.rfc-editor.org/rfc/rfc9457.html)) see existing [Error Handling documentation](https://ukhsa-collaboration.github.io/api-guidelines/api-design-guidelines/error-handling/) for additional details on the Problem details standard.

### Acceptance Criteria
If common error responses are not present for all operations in the APIs OpenAPI definition then it should fail the spectral linting with an appropriate error.

If an individual operation has no authentication such as the root (version information) operation or the entire API has no authentication then they MUST NOT require examples for `401` and `403` but should still include examples for `404` and `500`.

If the API itself has authentication it is possible to work if an individual operation has been excluded for authentication by looking for an empty security list.

``` yaml
paths:
  /:
    get:
      summary: Get API information.
      # the following security field set to an empty array removes any security schema for this endpoint/operation, that may have been applied to the API
      security: [] 
      description: Get API information.
      operationId: getApiInfo
      tags:
        - API Meta Information
      ...
```
you can use this information to create the appropriate condition for some of the examples.

### Example error message

`Each operation MUST include a all error response that combines multiple errors and must include examples for the common errors XXX, XXX, 404, 500`
